-- ----------------------------
-- Table structure for s7realdbstorage
-- ----------------------------
DROP TABLE IF EXISTS `{Database}`.`{TableName}`;
CREATE TABLE `{Database}`.`{TableName}` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `CreateTime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation time',
  `UpdateTime` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update time',
  `bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `byte` tinyint UNSIGNED NULL DEFAULT NULL COMMENT 'BYTE field',
  `char` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CHAR field',
  `sint` tinyint NULL DEFAULT NULL COMMENT 'SINT field',
  `int` int NULL DEFAULT NULL COMMENT 'INT field',
  `dint` int NULL DEFAULT NULL COMMENT 'DINT field',
  `lint` bigint NULL DEFAULT NULL COMMENT 'LINT field',
  `usint` tinyint UNSIGNED NULL DEFAULT NULL COMMENT 'USINT field',
  `uint` int UNSIGNED NULL DEFAULT NULL COMMENT 'UINT field',
  `udint` int UNSIGNED NULL DEFAULT NULL COMMENT 'UDINT field',
  `ulint` bigint UNSIGNED NULL DEFAULT NULL COMMENT 'ULINT field',
  `real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `lreal` double NULL DEFAULT NULL COMMENT 'LREAL field',
  `word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `dword` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'DWORD field',
  `lword` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'LWORD field',
  `string` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'STRING field',
  `date` date NULL DEFAULT NULL COMMENT 'DATE field',
  `time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'TIME field',
  `datetime` datetime NULL DEFAULT NULL COMMENT 'DATETIME field',
  `dtl` datetime NULL DEFAULT NULL COMMENT 'DTL field',
  `bit组` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'BOOL array (length:4)',
  `byte组` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'BYTE array (length:4)',
  `char组` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CHAR array (length:4)',
  `sint组` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'SINT array (length:3)',
  `int组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'INT array (length:4)',
  `dint组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'DINT array (length:3)',
  `lint组` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'LINT array (length:3)',
  `usint组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'USINT array (length:3)',
  `uint组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UINT array (length:4)',
  `udint组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UDINT array (length:3)',
  `ulint组` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'ULINT array (length:3)',
  `real组` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'REAL array (length:4)',
  `lreal组` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'LREAL array (length:3)',
  `word组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD array (length:4)',
  `dword组` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'DWORD array (length:3)',
  `lword组` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'LWORD array (length:3)',
  `date组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'DATE array (length:3)',
  `time组` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'TIME array (length:3)',
  `datetime组` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'DATETIME array (length:3)',
  `dtl组` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'DTL array (length:3)',
  `结构体[0].嵌套[0].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[0].嵌套[0].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[0].嵌套[0].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[0].嵌套[0].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[0].嵌套[1].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[0].嵌套[1].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[0].嵌套[1].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[0].嵌套[1].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[0].嵌套[2].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[0].嵌套[2].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[0].嵌套[2].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[0].嵌套[2].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[0].嵌套[3].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[0].嵌套[3].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[0].嵌套[3].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[0].嵌套[3].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[1].嵌套[0].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[1].嵌套[0].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[1].嵌套[0].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[1].嵌套[0].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[1].嵌套[1].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[1].嵌套[1].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[1].嵌套[1].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[1].嵌套[1].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[1].嵌套[2].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[1].嵌套[2].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[1].嵌套[2].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[1].嵌套[2].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[1].嵌套[3].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[1].嵌套[3].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[1].嵌套[3].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[1].嵌套[3].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[2].嵌套[0].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[2].嵌套[0].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[2].嵌套[0].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[2].嵌套[0].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[2].嵌套[1].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[2].嵌套[1].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[2].嵌套[1].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[2].嵌套[1].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[2].嵌套[2].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[2].嵌套[2].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[2].嵌套[2].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[2].嵌套[2].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[2].嵌套[3].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[2].嵌套[3].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[2].嵌套[3].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[2].嵌套[3].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[3].嵌套[0].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[3].嵌套[0].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[3].嵌套[0].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[3].嵌套[0].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[3].嵌套[1].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[3].嵌套[1].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[3].嵌套[1].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[3].嵌套[1].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[3].嵌套[2].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[3].嵌套[2].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[3].嵌套[2].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[3].嵌套[2].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `结构体[3].嵌套[3].bit` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `结构体[3].嵌套[3].byte` tinyint NULL DEFAULT NULL COMMENT 'BYTE field',
  `结构体[3].嵌套[3].word` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'WORD field',
  `结构体[3].嵌套[3].real` float NULL DEFAULT NULL COMMENT 'REAL field',
  `bit_1` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_2` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_3` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_4` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_5` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_6` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_7` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_8` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_9` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  `bit_10` tinyint(1) NULL DEFAULT 0 COMMENT 'BOOL field',
  PRIMARY KEY (`ID`) USING BTREE
)
COMMENT = '{Comment}';